/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#2d443b",
        outline: "#787b7a",
        error: "#a83836",
        "surface-bright": "#faf9f8",
        "on-tertiary": "#edfbff",
        "on-primary-container": "#175c49",
        surface: "#faf9f8",
        "on-secondary": "#e5fff2",
        "on-error-container": "#6e0a12",
        "surface-container-low": "#f3f4f3",
        "tertiary-fixed": "#b7effb",
        "surface-container": "#edeeed",
        "primary-fixed-dim": "#a0e2c9",
        "primary-dim": "#195e4a",
        "on-tertiary-container": "#205b65",
        "secondary-fixed": "#cee9dc",
        "on-secondary-fixed-variant": "#496057",
        primary: "#286a56",
        "outline-variant": "#b0b2b1",
        "on-primary-fixed": "#004937",
        "on-primary-fixed-variant": "#246652",
        "error-container": "#fa746f",
        "surface-tint": "#286a56",
        "on-background": "#303333",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#2c656f",
        "on-tertiary-fixed": "#034852",
        "on-primary": "#e5fff2",
        "primary-container": "#aef0d6",
        background: "#faf9f8",
        "on-secondary-container": "#3f574d",
        tertiary: "#2e6771",
        "inverse-primary": "#bcffe4",
        "inverse-surface": "#0d0e0e",
        "secondary-fixed-dim": "#c0dace",
        "surface-variant": "#e1e3e2",
        "on-surface-variant": "#5d605f",
        "tertiary-fixed-dim": "#a9e0ec",
        "surface-container-high": "#e7e8e7",
        "surface-dim": "#d8dad9",
        "error-dim": "#67040d",
        "tertiary-dim": "#205a65",
        "surface-container-highest": "#e1e3e2",
        "tertiary-container": "#b7effb",
        "on-error": "#fff7f6",
        "secondary-dim": "#40584f",
        "primary-fixed": "#aef0d6",
        "secondary-container": "#cee9dc",
        "inverse-on-surface": "#9d9d9c",
        "on-surface": "#303333",
        secondary: "#4c645a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
